apiVersion: v1
kind: Pod
metadata:
  name: mysql-configmap1
spec:
  containers:
    - name: conl
      image: mysql:5.6
      ports:
        - containerPort: 3306
      env:
        # Define the environment variable
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
            # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
               name: db-user-pass
            # Specify the key associated with the value
               key: password
            
