apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  user: user1
  pass: ebs123
  rootpass: bs123
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-configmap3
spec:
  containers:
    - name: con2
      image: mysql:5.6
      ports:
        - containerPort: 3307
      env:
        # Define the environment variable
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                  name: special-config
              # Specify the key associated with the value
                  key: pass
