apiVersion: v1
kind: Pod
metadata:
  name: test-pd3
spec: 
  containers:
  - image: nginx
    name: test-container3
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    # This GCE PD must already exist.
    gcePersistentDisk:
      pdName: mydisk1
      fsType: ext4
