apiVersion: v1
kind: Pod
metadata:
  name: test-pd2
spec:
  containers:
  - image: nginx:1.16
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume1
  volumes:
  - name: test-volume1
    hostPath:
      #directory location on host
      path: /tmp
      #this feild is optional
      type: Directory
