apiVersion: batch/v1
kind: Job
metadata:
  name: jobs-1
spec:
  template:
    spec:
      containers:
        - name:  pi
          image: perl
          command: ["eeecho", "Hello World !!!!!"]
      restartPolicy: Never
  backoffLimit: 4
