apiVersion: batch/v1
kind: Job
metadata:
  name: jobs
spec:
  template:
    spec:
     containers:
       - name: pi
         image: perl
         command: ["echo", "Hello World !!!!!"]
     restartPolicy: Never
