apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-servic
spec:
  selector:
    app:  web
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30036
