apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy2
  namespace: default
spec:
  podSelector:
    matchLabels:
      prod: web
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          dev: web
