apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: name-virtual-host-ingress
spec:
  rules:
  - host: chiti.robo.com
    http:
      paths:
      - backend:
          serviceName: nginx-service
          servicePort: 5000
  - host: pakshi.robo.com
    http:
      paths:
      - backend:
          serviceName: apache-service
          servicePort: 5001

